import { Seller } from "./types";

export const SELLERS: Seller[] = [
  {
    id: "1",
    slug: "webb-woodworks",
    name: "Webb Woodworks",
    tagline: "Handcrafted furniture and heirloom pieces from Idaho timber",
    bio: "Marcus Webb has been working wood in his Post Falls shop for over fifteen years. Every piece starts with locally sourced timber — mostly white oak, ponderosa pine, and black walnut from North Idaho mills. He builds furniture meant to outlast the people who own it, with joinery techniques that don't need glue or hardware to hold.",
    location_label: "Post Falls",
    lat: 47.7182,
    lng: -116.9457,
    categories: ["Wood & Craft"],
    cover_photo_url: "https://images.unsplash.com/photo-1530124566582-a618bc2615dc?w=1200&q=80",
    profile_photo_url: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=200&q=80",
    accepted_payments: ["Cash", "Venmo", "PayPal"],
    barter_accepts: "Fresh produce, farm eggs, quality hand tools, locally milled lumber",
    delivery_available: true,
    delivery_radius_miles: 25,
    custom_orders_open: true,
    community_contributor: true,
    featured: true,
    verified: true,
    products: [
      {
        id: "p1",
        title: "Live-Edge Dining Table",
        description: "Black walnut slab, hand-planed and finished with hardwax oil. Seats 6–8. Custom sizing available.",
        price: 2400,
        photo_url: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800&q=80",
        category: "Wood & Craft",
        availability_status: "made_to_order",
      },
      {
        id: "p2",
        title: "End-Grain Cutting Board",
        description: "Maple and walnut checkerboard pattern. Each one is unique. Ready to ship.",
        price: 85,
        photo_url: "https://images.unsplash.com/photo-1593030761757-71fae45fa0e7?w=800&q=80",
        category: "Wood & Craft",
        availability_status: "available",
      },
      {
        id: "p3",
        title: "Floating Shelf Set (3)",
        description: "Ponderosa pine with natural live edge. Handmade bracket hardware. Available in natural or dark oil finish.",
        price: 180,
        photo_url: "https://images.unsplash.com/photo-1618220179428-22790b461013?w=800&q=80",
        category: "Wood & Craft",
        availability_status: "available",
      },
    ],
  },
  {
    id: "2",
    slug: "holbrook-family-farm",
    name: "Holbrook Family Farm",
    tagline: "Pasture-raised eggs, raw honey, and seasonal produce from Rathdrum Prairie",
    bio: "The Holbrook family has farmed outside Rathdrum for three generations. They run a small flock of heritage breed chickens on open pasture, two hives of honeybees, and a large kitchen garden that produces more than the family can eat from May through October. Everything is grown without synthetic pesticides or herbicides.",
    location_label: "Rathdrum",
    lat: 47.8128,
    lng: -116.8957,
    categories: ["Food & Farm"],
    cover_photo_url: "https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=1200&q=80",
    profile_photo_url: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&q=80",
    accepted_payments: ["Cash", "Venmo", "Cash App"],
    barter_accepts: "Handmade goods, quality seeds, canning supplies, firewood",
    delivery_available: true,
    delivery_radius_miles: 15,
    custom_orders_open: false,
    community_contributor: false,
    featured: true,
    verified: true,
    products: [
      {
        id: "p4",
        title: "Pasture-Raised Eggs",
        description: "One dozen. Hens rotate daily on fresh grass. Yolks run deep orange. Pickup or local delivery.",
        price: 8,
        price_label: "per dozen",
        photo_url: "https://images.unsplash.com/photo-1582722872445-44dc5f7e3c8f?w=800&q=80",
        category: "Food & Farm",
        availability_status: "available",
      },
      {
        id: "p5",
        title: "Raw Wildflower Honey",
        description: "Unfiltered, unheated. Harvested from hives on Rathdrum Prairie. 16 oz jar.",
        price: 18,
        price_label: "per jar",
        photo_url: "https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=800&q=80",
        category: "Food & Farm",
        availability_status: "available",
      },
      {
        id: "p6",
        title: "Seasonal Veggie Box",
        description: "Mixed seasonal vegetables from the kitchen garden. Changes weekly. Available June through October.",
        price: 25,
        photo_url: "https://images.unsplash.com/photo-1540420773420-3366772f4999?w=800&q=80",
        category: "Food & Farm",
        availability_status: "seasonal",
      },
    ],
  },
  {
    id: "3",
    slug: "cedar-and-stone",
    name: "Cedar & Stone Apothecary",
    tagline: "Small-batch candles, tinctures, and soaps made with foraged and garden-grown ingredients",
    bio: "Maeve Collins started Cedar & Stone in her Coeur d'Alene kitchen after years of wildcrafting herbs in the Idaho panhandle. She makes everything in small batches — 24 to 48 units at a time — using beeswax from a local beekeeper, tallow she renders herself, and herbs she grows or forages within 20 miles of home. Nothing here is manufactured at scale.",
    location_label: "Coeur d'Alene",
    lat: 47.6777,
    lng: -116.7805,
    categories: ["Apothecary & Wellness"],
    cover_photo_url: "https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?w=1200&q=80",
    profile_photo_url: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200&q=80",
    accepted_payments: ["Cash", "Venmo", "PayPal", "Cash App"],
    barter_accepts: "Fresh herbs, foraged mushrooms, beeswax, tallow, quality dried botanicals",
    delivery_available: true,
    delivery_radius_miles: 20,
    custom_orders_open: true,
    community_contributor: true,
    featured: true,
    verified: true,
    products: [
      {
        id: "p7",
        title: "Beeswax + Cedar Candle",
        description: "8 oz. Pure beeswax from a Rathdrum beekeeper, scented with Idaho cedar and wild sage. Burns 40+ hours.",
        price: 28,
        photo_url: "https://images.unsplash.com/photo-1602178496-75949099f3ad?w=800&q=80",
        category: "Apothecary & Wellness",
        availability_status: "available",
      },
      {
        id: "p8",
        title: "Pine & Calendula Bar Soap",
        description: "Cold-process. Tallow base, infused with foraged pine resin and garden-grown calendula. Unscented.",
        price: 12,
        photo_url: "https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?w=800&q=80",
        category: "Apothecary & Wellness",
        availability_status: "available",
      },
      {
        id: "p9",
        title: "Sleep Tincture",
        description: "Valerian, passionflower, and lemon balm in organic cane spirits. 2 oz dropper bottle. Third-party lab tested.",
        price: 32,
        photo_url: "https://images.unsplash.com/photo-1471943311424-646960669fbc?w=800&q=80",
        category: "Apothecary & Wellness",
        availability_status: "available",
      },
    ],
  },
  {
    id: "4",
    slug: "ironwood-forge",
    name: "Ironwood Forge",
    tagline: "Hand-forged tools, garden art, and custom ironwork from a working Hayden smithy",
    bio: "Dale Sorenson learned to forge from his grandfather in rural Montana and has run Ironwood Forge outside Hayden for twelve years. He works primarily in recycled and salvaged steel, builds everything to be used rather than displayed, and takes custom work ranging from garden gates to kitchen knives to decorative hardware for timber frame homes.",
    location_label: "Hayden",
    lat: 47.7657,
    lng: -116.7863,
    categories: ["Metal & Forge"],
    cover_photo_url: "https://images.unsplash.com/photo-1612214153254-d93c4c3a05e6?w=1200&q=80",
    profile_photo_url: "https://images.unsplash.com/photo-1560250097-0b93528c311a?w=200&q=80",
    accepted_payments: ["Cash", "Venmo"],
    barter_accepts: "Quality hardwoods, leather, quality hand tools, food",
    delivery_available: false,
    delivery_radius_miles: 0,
    custom_orders_open: true,
    community_contributor: false,
    featured: false,
    verified: true,
    products: [
      {
        id: "p10",
        title: "Hand-Forged Garden Fork",
        description: "Four-tine digging fork. Mild steel, octagonal handle socket, hardwood handle. Built to last generations.",
        price: 145,
        photo_url: "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=800&q=80",
        category: "Metal & Forge",
        availability_status: "made_to_order",
      },
      {
        id: "p11",
        title: "Forged Steak Knives (Set of 4)",
        description: "High-carbon steel, hand-ground edge, walnut handles with copper rivets. Each set slightly unique.",
        price: 220,
        photo_url: "https://images.unsplash.com/photo-1556909172-54557c7e4fb7?w=800&q=80",
        category: "Metal & Forge",
        availability_status: "available",
      },
    ],
  },
  {
    id: "5",
    slug: "blue-heron-fiber",
    name: "Blue Heron Fiber",
    tagline: "Hand-dyed yarn, woven textiles, and heirloom quilts from a Sandpoint studio",
    bio: "Annie Mikkelsen dyes yarn with plants she grows and gathers in Bonner County, weaves on a floor loom that belonged to her grandmother, and pieces quilts from reclaimed and vintage fabric when she can find it. Her color palette comes from what the Idaho landscape gives her each season — it changes, and she leans into that.",
    location_label: "Sandpoint",
    lat: 48.2766,
    lng: -116.5535,
    categories: ["Fiber & Textile"],
    cover_photo_url: "https://images.unsplash.com/photo-1558769132-cb1aea458c5e?w=1200&q=80",
    profile_photo_url: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=200&q=80",
    accepted_payments: ["Cash", "Venmo", "PayPal"],
    barter_accepts: "Raw fleece, natural dye materials, quality vintage fabric, wool roving",
    delivery_available: true,
    delivery_radius_miles: 10,
    custom_orders_open: true,
    community_contributor: true,
    featured: false,
    verified: true,
    products: [
      {
        id: "p12",
        title: "Plant-Dyed Worsted Yarn",
        description: "100% Rambouillet wool, hand-dyed with black walnut, madder, or weld. 200 yards per skein. Colorway varies.",
        price: 38,
        price_label: "per skein",
        photo_url: "https://images.unsplash.com/photo-1588345921523-c2dcdb7f1dcd?w=800&q=80",
        category: "Fiber & Textile",
        availability_status: "available",
      },
      {
        id: "p13",
        title: "Linen + Cotton Table Runner",
        description: "Hand-woven on a 4-shaft loom. Natural undyed linen warp, plant-dyed cotton weft. 14\" × 72\".",
        price: 95,
        photo_url: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80",
        category: "Fiber & Textile",
        availability_status: "available",
      },
    ],
  },
  {
    id: "6",
    slug: "north-country-ceramics",
    name: "North Country Ceramics",
    tagline: "Functional stoneware for everyday life, thrown and fired in Coeur d'Alene",
    bio: "Jess Park throws wheel-thrown stoneware in a small studio off 4th Street in CDA. She fires in a wood-kiln she built herself with a friend, which gives her work its characteristic ash deposits and unpredictable surface variation. Every mug, bowl, and planter is made to be handled daily, not displayed on a shelf.",
    location_label: "Coeur d'Alene",
    lat: 47.6688,
    lng: -116.7800,
    categories: ["Art & Photography"],
    cover_photo_url: "https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?w=1200&q=80",
    profile_photo_url: "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=200&q=80",
    accepted_payments: ["Cash", "Venmo", "PayPal", "Cash App"],
    barter_accepts: "Quality food, handmade goods, garden produce, good books",
    delivery_available: true,
    delivery_radius_miles: 15,
    custom_orders_open: true,
    community_contributor: false,
    featured: false,
    verified: true,
    products: [
      {
        id: "p14",
        title: "Wood-Fire Mug",
        description: "14 oz. Stoneware, wood-kiln fired. Natural ash glaze with iron-oxide liner. Each one unique.",
        price: 48,
        photo_url: "https://images.unsplash.com/photo-1514228742587-6b1558fcca3d?w=800&q=80",
        category: "Art & Photography",
        availability_status: "available",
      },
      {
        id: "p15",
        title: "Nesting Bowl Set",
        description: "Three sizes. Stoneware with celadon glaze. Microwave and dishwasher safe.",
        price: 110,
        photo_url: "https://images.unsplash.com/photo-1610701596061-2ecf227e85b2?w=800&q=80",
        category: "Art & Photography",
        availability_status: "available",
      },
      {
        id: "p16",
        title: "Planter with Drainage Tray",
        description: "6\" stoneware planter. Textured exterior, glazed interior and tray. Frost-resistant for Idaho winters.",
        price: 65,
        photo_url: "https://images.unsplash.com/photo-1485955900006-10f4d324d411?w=800&q=80",
        category: "Art & Photography",
        availability_status: "available",
      },
    ],
  },
  {
    id: "7",
    slug: "painted-hills-garden",
    name: "Painted Hills Garden",
    tagline: "Heirloom seedlings, potted herbs, and garden starts grown from open-pollinated seed",
    bio: "Sam and Rosa Deluca started Painted Hills Garden on a half-acre outside Post Falls to grow the plants they couldn't find at garden centers — rare tomatoes, unusual basil varieties, heat-tolerant lettuces adapted to Idaho summers. Everything is started from open-pollinated or heirloom seed they save or source from small regional seed companies.",
    location_label: "Post Falls",
    lat: 47.7290,
    lng: -116.9671,
    categories: ["Garden & Plant"],
    cover_photo_url: "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=1200&q=80",
    profile_photo_url: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&q=80",
    accepted_payments: ["Cash", "Venmo", "Barter"],
    barter_accepts: "Seeds, compost, garden tools, fruit, eggs — basically anything from a garden or farm",
    delivery_available: true,
    delivery_radius_miles: 20,
    custom_orders_open: true,
    community_contributor: false,
    featured: false,
    verified: true,
    products: [
      {
        id: "p17",
        title: "Heirloom Tomato Starts (6-Pack)",
        description: "Mix of 2–3 varieties based on availability: Brandywine, Cherokee Purple, Green Zebra. 4\" pots, ready to transplant.",
        price: 18,
        price_label: "per 6-pack",
        photo_url: "https://images.unsplash.com/photo-1592921870789-04563d55041c?w=800&q=80",
        category: "Garden & Plant",
        availability_status: "seasonal",
      },
      {
        id: "p18",
        title: "Herb Garden Starter Kit",
        description: "Five 4\" pots: basil, parsley, thyme, oregano, chives. All from seed, all organic inputs.",
        price: 22,
        photo_url: "https://images.unsplash.com/photo-1466692476868-aef1dfb1e735?w=800&q=80",
        category: "Garden & Plant",
        availability_status: "seasonal",
      },
    ],
  },
  {
    id: "8",
    slug: "lost-creek-honey",
    name: "Lost Creek Honey",
    tagline: "Raw varietal honey and beeswax products from Rathdrum Prairie hives",
    bio: "Bret Ellis keeps twelve hives on the prairie east of Rathdrum and has been running bees in North Idaho for eight years. He harvests once a year in late August, keeps everything raw and unfiltered, and offers his honey by the varietal when the season allows — clover, wildflower, and buckwheat depending on what bloomed. The beeswax goes into candles and wood finish he makes through the winter.",
    location_label: "Rathdrum",
    lat: 47.8200,
    lng: -116.8750,
    categories: ["Food & Farm", "Apothecary & Wellness"],
    cover_photo_url: "https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=1200&q=80",
    profile_photo_url: "https://images.unsplash.com/photo-1504257432389-52343af06ae3?w=200&q=80",
    accepted_payments: ["Cash", "Venmo"],
    barter_accepts: "Fruit, garden produce, eggs, firewood, handmade goods",
    delivery_available: false,
    delivery_radius_miles: 0,
    custom_orders_open: false,
    community_contributor: false,
    featured: false,
    verified: true,
    products: [
      {
        id: "p19",
        title: "Raw Clover Honey",
        description: "Light, mild, classic. Harvested from hives near alfalfa and clover fields on the prairie. 16 oz.",
        price: 16,
        price_label: "per jar",
        photo_url: "https://images.unsplash.com/photo-1471943311424-646960669fbc?w=800&q=80",
        category: "Food & Farm",
        availability_status: "available",
      },
      {
        id: "p20",
        title: "Raw Buckwheat Honey",
        description: "Dark, bold, mineral. Not for everyone — but the people who love it really love it. 16 oz.",
        price: 20,
        price_label: "per jar",
        photo_url: "https://images.unsplash.com/photo-1558642452-9d2a7deb7f62?w=800&q=80",
        category: "Food & Farm",
        availability_status: "seasonal",
      },
      {
        id: "p21",
        title: "Beeswax Wood Finish",
        description: "Pure beeswax melted with linseed oil. Feed and protect cutting boards, butcher blocks, and wood tools. 4 oz tin.",
        price: 14,
        photo_url: "https://images.unsplash.com/photo-1618220179428-22790b461013?w=800&q=80",
        category: "Apothecary & Wellness",
        availability_status: "available",
      },
    ],
  },
];

export const FEATURED_SELLERS = SELLERS.filter((s) => s.featured);
export const getSeller = (slug: string) => SELLERS.find((s) => s.slug === slug);
